# Generated by Django 3.0.7 on 2020-06-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='choice',
            field=models.CharField(max_length=50),
        ),
    ]
